In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])


result_addition  = array1 + array2
# print(type(array1 + array2))

result_subtraction = array1 - array2
result_multiplication = array1 * array2
result_division = array1 / array2

print("Addition", result_addition)
print("Subtraction", result_subtraction)
print("Multiplication", result_multiplication)
print("Division", result_division)


# square root
result_sqrt = np.sqrt(array1)
print("Square root", result_sqrt)

# Summation
result_summation = np.sum(array1)
print("Summation", result_summation)

# Mean (Average)
result_mean = np.mean(array1)
print("Mean", result_mean)

# max
result_max = np.max(array1)
print("Max", result_max)

#min   
result_min = np.min(array1)
print("Min", result_min)


Addition [ 7  9 11 13 15]
Subtraction [-5 -5 -5 -5 -5]
Multiplication [ 6 14 24 36 50]
Division [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Square root [1.         1.41421356 1.73205081 2.         2.23606798]
Summation 15
Mean 3.0
Max 5
Min 1


In [9]:
import numpy as np
array_2d = np.array([[1,3,2], [4,5,6], [7,8,9]])
print(array_2d)
print(type(array_2d))
print(len(array_2d))
result_size = np.size(array_2d)
print("Size", result_size)
result_shape = np.shape(array_2d)
print("Shape", result_shape)

[[1 3 2]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
3
Size 9
Shape (3, 3)


In [16]:
import numpy as np

array_3D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ])
print(array_3D)
array3D_shape = np.shape(array_3D)
print("Shape", array3D_shape)

print(array_3D.dtype)
print("ndim (Number of dimensions)", array_3D.ndim)

# Numpy Array Indexing
print(array_3D[0,0,1])
print(array_3D[0,0])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape (2, 2, 3)
int64
ndim (Number of dimensions) 3
2
[1 2 3]


In [27]:
import numpy as np 

# add every element a 10
array_2D = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])
print("2D Array",array_2D)
array_2D = array_2D + 10
print("Elements added 10", array_2D)

array_2D_2 = array_2D * 2
print("Elements multiplied by 2", array_2D_2)

array_2D_3 = np.sqrt(array_2D)
print("Square root of every element", array_2D_3)

array_2D_4 = array_2D**2
print("Square of every element", array_2D_4)

2D Array [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Elements added 10 [[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
Elements multiplied by 2 [[22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]
 [52 54 56 58 60]]
Square root of every element [[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]
 [4.         4.12310563 4.24264069 4.35889894 4.47213595]
 [4.58257569 4.69041576 4.79583152 4.89897949 5.        ]
 [5.09901951 5.19615242 5.29150262 5.38516481 5.47722558]]
Square of every element [[121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]
 [676 729 784 841 900]]


In [32]:
import numpy as np

arr = np.array([10,20,30,40,50])
condititon = arr > 25
print(condititon)

filtered = arr[condititon]
print(filtered)


[False False  True  True  True]
[30 40 50]


In [35]:
import numpy as np

arr2 = np.array([10,20,30,40,50])
filtered_array = arr2[arr2 > 25]
print("Filtered Array : ",filtered_array)

Filtered Array :  [30 40 50]


In [37]:
import numpy as np

arr = np.array([10,20,30,40,50])
filtered_combined = arr[(arr > 20) & (arr < 50)]
print("Filtered Combined : ",filtered_combined)

Filtered Combined :  [30 40]


In [48]:
import numpy as np

array_1 = np.zeros(5)
print("Zeros", array_1)

array_2 = np.ones(5)
print("Ones", array_2)

array_3 = np.full(5, 5)
print("Full", array_3)

array_4 = np.eye(5)
print("Identity", array_4)


array_5 = np.random.random(5)
print("Random", array_5)


array_6 = np.zeros((3,3))
print("Zeros 2D", array_6)

array_7 = np.full((4,3), 5)
print("Full 2D", array_7)

array_8 = np.empty((2,3))
print("Empty 2D : Garbage Values : ", array_8)

Zeros [0. 0. 0. 0. 0.]
Ones [1. 1. 1. 1. 1.]
Full [5 5 5 5 5]
Identity [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Random [0.21334055 0.91537068 0.3936642  0.92069788 0.49252533]
Zeros 2D [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Full 2D [[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
Empty 2D : Garbage Values :  [[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


In [51]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
even_numbers = array[array % 2 == 0]
print("Even Numbers : ", even_numbers)


array_1 = np.array([10,20,30,40,50])
# extract all elements greater than the mean
mean_result = np.mean(array_1)
greater_than_mean = array_1[array_1 > mean_result]
print("Mean : ", greater_than_mean)

Even Numbers :  [ 2  4  6  8 10 12 14 16 18 20]
Mean :  [40 50]
